#!/usr/bin/env bash
# This script is for installing OLM from a GitHub release
set -eu
cd "$(dirname "$0")/.."

default_base_url=https://github.com/operator-framework/operator-lifecycle-manager/releases/download

if [[ ${#@} -lt 1 || ${#@} -gt 2 ]]; then
    echo "Usage: $0 version [base_url]"
    echo "* version: the github release version"
    echo "* base_url: the github base URL (Default: $default_base_url)"
    exit 1
fi

if auto/kubectl get deployment olm-operator -n openshift-operator-lifecycle-manager > /dev/null 2>&1; then
    echo "OLM is already installed in a different configuration. This is common if you are not running a vanilla Kubernetes cluster. Exiting..."
    exit 1
fi

default_version="0.24.0"
release="${1:-${default_version}}"
base_url="${2:-${default_base_url}}"
url="${base_url}/${release}"
namespace=olm

if auto/kubectl get deployment olm-operator -n ${namespace} > /dev/null 2>&1; then
    echo "OLM is already installed in ${namespace} namespace. Exiting..."
    exit 1
fi

auto/kubectl create -f "${url}/crds.yaml"
auto/kubectl wait --for=condition=Established -f "${url}/crds.yaml"
auto/kubectl create -f "${url}/olm.yaml"

# wait for deployments to be ready
auto/kubectl rollout status -w deployment/olm-operator --namespace="${namespace}"
auto/kubectl rollout status -w deployment/catalog-operator --namespace="${namespace}"

sleep 60

auto/kubectl rollout status -w deployment/packageserver --namespace="${namespace}"
